### ISSUE TITLE
注解形式的动态sql（即使用了@XXXProvider）报错，是否支持这种注解动态sql写法呢？

### ISSUE THREAD

**Issue by GrayOxygen** [pagehelper/Mybatis-PageHelper#101]
在使用下面的selectByUserName查询时，没有问题。如下是我的动态provider
```java
public class DynamicProvider {
		private static final String TABLE_NAME = "user_info";

		public String insert(final UserInfo user) {
			return new SQL() {
				{
					INSERT_INTO(TABLE_NAME);
					VALUES("USER_ID, USER_NAME, MOBILE","#{userId,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}");  
					VALUES("TEL_NO, EMAIL, ADDRESS ","#{telNo,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}");  
					VALUES("BIRTHDAY, GENDER, USER_STATUS","#{birthday,jdbcType=DATE}, #{gender,jdbcType=CHAR}, #{userStatus,jdbcType=INTEGER}");  
					VALUES("USER_TYPE,RONG_CLOUD_TOKEN , CHANNEL_ID  ", "#{userType,jdbcType=INTEGER},#{rongCloudToken,jdbcType=VARCHAR}, #{channelId,jdbcType=VARCHAR} "); 
					VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
				}
			}.toString();
		}

		public String selectByUserName(String userName) {
			return new SQL() {
				{
					SELECT("USER_ID", "USER_NAME", "MOBILE", "TEL_NO", "EMAIL", "ADDRESS", "BIRTHDAY", "GENDER",
							"USER_STATUS", "USER_TYPE", "RONG_CLOUD_TOKEN", "CHANNEL_ID");
					FROM(TABLE_NAME);
					WHERE("USER_NAME LIKE #{userName,jdbcType=VARCHAR}");

				}
			}.toString();
		}
	}
```
使用的时候是
```java
	@ResultMap(value = { "BaseResultMap" })
	@SelectProvider(type = DynamicProvider.class, method = "selectByUserName")
	List<UserInfo> selectByUserName(String userName);
```

但是使用咱们的分页时就报错，比如下面这种写法
```java
userInfoMapper.findPage(() -> userInfoMapper.selectByUserName("%阳%"), pageInfo);
```
报错的完整信息如下
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'providerTakesParameterObject' in 'class org.apache.ibatis.builder.annotation.ProviderSqlSource'
    at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
    at com.sun.proxy.$Proxy115.selectList(Unknown Source)
    at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
    at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
    at com.sun.proxy.$Proxy128.selectByUserName(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy131.selectByUserName(Unknown Source)
    at com.houniao.microservice.user.mapper.UserMapperTest.lambda$0(UserMapperTest.java:129)
    at com.github.pagehelper.Page.doSelectPageInfo(Page.java:350)
    at com.houniao.microservice.base.mapper.BaseMapper.findPage(BaseMapper.java:34)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
    at org.apache.ibatis.binding.MapperProxy.invokeDefaultMethod(MapperProxy.java:84)
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
    at com.sun.proxy.$Proxy128.findPage(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy131.findPage(Unknown Source)
    at com.houniao.microservice.user.mapper.UserMapperTest.findPage(UserMapperTest.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'providerTakesParameterObject' in 'class org.apache.ibatis.builder.annotation.ProviderSqlSource'
    at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:421)
    at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164)
    at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
    at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
    at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
    at com.github.pagehelper.sqlsource.PageProviderSqlSource.<init>(PageProviderSqlSource.java:58)
    at com.github.pagehelper.SqlUtil.processMappedStatement(SqlUtil.java:309)
    at com.github.pagehelper.SqlUtil.doProcessPage(SqlUtil.java:461)
    at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:408)
    at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:375)
    at com.github.pagehelper.PageHelper.intercept(PageHelper.java:252)
    at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
    at com.sun.proxy.$Proxy156.query(Unknown Source)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
    ... 58 more
```

**Comment by abel533** [comment]
mybatis各种依赖版本分别是多少？

**Comment by GrayOxygen** [comment]
@abel533 
基于spring boot搭建的，相关依赖如下
	
		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
			<version>1.3.0</version>
			<exclusions>
				<exclusion>
					<artifactId>logback-classic</artifactId>
					<groupId>ch.qos.logback</groupId>
				</exclusion>
			</exclusions>
			
		</dependency>


		
		<dependency>
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper</artifactId>
			<version>4.1.1</version>
		</dependency>

**Comment by abel533** [comment]
先升级分页插件到4.2.x或者5.x再试试。
