### ISSUE TITLE
spring boot单元测试分页报错，list无法被转换为page，拦截器没有生效么？

### ISSUE THREAD

**Issue by abnerbos** [pagehelper/Mybatis-PageHelper#107]
springboot工程分页正常，但是单元测试中测试同样的方法报错，错误为：

java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.github.pagehelper.Page

单元测试的注解如下：
@RunWith(SpringRunner.class)
@Import(XXXXServiceConfiguration.class)
@TestPropertySource("classpath:application.properties")
@MybatisTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)

由于注解的存在，覆盖的单元测试中的sql也应该用到了代理，是否和pageHelper的拦截器代理冲突了？

**Comment by abel533** [comment]
用的 pageHelper-starter ? 怎么配置的拦截器？

**Comment by abnerbos** [comment]
嗯   用的starter 
<dependency>
			<groupId>com.github.pagehelper</groupId>
			<artifactId>pagehelper-spring-boot-starter</artifactId>
			<version>1.1.3</version>
		</dependency>

没有显示的去配置pageHelper的拦截器，直接在代码中用的  PageHelper.startPage(page, pageSize);

**Comment by abel533** [comment]
能不能提供上面错误信息的完整堆栈信息？

**Comment by abnerbos** [comment]
我这边的使用情况是，自己定义了 PageBean，将查询到的结果 list直接 强转为Page类型，报的错也是 转换失败，具体的异常为

java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.github.pagehelper.Page

	at com.yqg.loanmarket.service.impl.BannerServiceImpl.getBannerVOListByStatus(BannerServiceImpl.java:44)
	at com.yqg.loanmarket.service.impl.BannerServiceImplTest.testGetBannerListByStatus(BannerServiceImplTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by abel533** [comment]
明白了。。你是不是有地方强转为 Page 类型，但实际上你这里不是分页后的结果。

**Comment by abnerbos** [comment]
这个是分页的结果，就是 PageHelper.startPage 之后执行的sql
直接启动工程，这个分页并且直接转换为 Page是 work的，
但是 在单元测试中报类型错误，由于单元测试中也存在 sql拦截，所以我怀疑是不是导致PageHelper没生效

**Comment by abnerbos** [comment]
具体代码如下：
PageHelper.startPage(page, pageSize);
    List<Banner> banners = bannerDao.getBannerListByStatus(status == null ? null : status.getCode(), page, pageSize);

    return new PageBean<>((Page<Banner>) banners, banners.stream().map(BannerConverter::convertToBannerVO).collect(Collectors.toList()));

**Comment by abel533** [comment]
输出的 SQL 经过分页了吗？

**Comment by abnerbos** [comment]
没有把SQL打出来，等会儿我打出来看一下，但是 打了断点，看了下查询结果的类型确实只是 LIST，不是Page

**Comment by abnerbos** [comment]
貌似sql 没有分页，输出的log 如下
`2017-08-27T22:11:52,453 DEBUG [main] org.mybatis.spring.SqlSessionUtils       (SqlSessionUtils.java:163) - Fetched SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@437281c5] from current transaction
2017-08-27T22:11:52,491 DEBUG [main] apper.BannerMapper.getBannerListByStatus (BaseJdbcLogger.java:159) - ==>  Preparing: SELECT * FROM banner WHERE status != -1 and status = ? ORDER BY score DESC 
2017-08-27T22:11:52,492 DEBUG [main] apper.BannerMapper.getBannerListByStatus (BaseJdbcLogger.java:159) - ==> Parameters: 1(Integer)
2017-08-27T22:11:52,515 DEBUG [main] apper.BannerMapper.getBannerListByStatus (BaseJdbcLogger.java:159) - <==      Total: 1
2017-08-27T22:11:52,516 DEBUG [main] org.mybatis.spring.SqlSessionUtils       (SqlSessionUtils.java:186) - Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@437281c5]
2017-08-27T22:11:52,517 DEBUG [main] e.DefaultCacheAwareContextLoaderDelegate (DefaultCacheAwareContextLoaderDelegate.java:129) - Retrieved ApplicationContext from cache with key [[MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2017-08-27T22:11:52,517 DEBUG [main] org.springframework.test.context.cache   (DefaultContextCache.java:290) - Spring test ApplicationContext cache statistics: [DefaultContextCache@5a7b309b size = 1, maxSize = 32, parentContextCount = 0, hitCount = 3, missCount = 1]
2017-08-27T22:11:52,518 DEBUG [main] e.DefaultCacheAwareContextLoaderDelegate (DefaultCacheAwareContextLoaderDelegate.java:129) - Retrieved ApplicationContext from cache with key [[MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2017-08-27T22:11:52,518 DEBUG [main] org.springframework.test.context.cache   (DefaultContextCache.java:290) - Spring test ApplicationContext cache statistics: [DefaultContextCache@5a7b309b size = 1, maxSize = 32, parentContextCount = 0, hitCount = 4, missCount = 1]
2017-08-27T22:11:52,519 DEBUG [main] e.DefaultCacheAwareContextLoaderDelegate (DefaultCacheAwareContextLoaderDelegate.java:129) - Retrieved ApplicationContext from cache with key [[MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2017-08-27T22:11:52,520 DEBUG [main] org.springframework.test.context.cache   (DefaultContextCache.java:290) - Spring test ApplicationContext cache statistics: [DefaultContextCache@5a7b309b size = 1, maxSize = 32, parentContextCount = 0, hitCount = 5, missCount = 1]
2017-08-27T22:11:52,521 DEBUG [main] ctory.support.DefaultListableBeanFactory (AbstractBeanFactory.java:251) - Returning cached instance of singleton bean 'org.springframework.boot.test.mock.mockito.MockitoBeans'
2017-08-27T22:11:52,521 DEBUG [main] e.DefaultCacheAwareContextLoaderDelegate (DefaultCacheAwareContextLoaderDelegate.java:129) - Retrieved ApplicationContext from cache with key [[MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2017-08-27T22:11:52,521 DEBUG [main] org.springframework.test.context.cache   (DefaultContextCache.java:290) - Spring test ApplicationContext cache statistics: [DefaultContextCache@5a7b309b size = 1, maxSize = 32, parentContextCount = 0, hitCount = 6, missCount = 1]
2017-08-27T22:11:52,523 DEBUG [main] org.mybatis.spring.SqlSessionUtils       (SqlSessionUtils.java:310) - Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@437281c5]
2017-08-27T22:11:52,523 DEBUG [main] org.mybatis.spring.SqlSessionUtils       (SqlSessionUtils.java:315) - Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@437281c5]
2017-08-27T22:11:52,523 DEBUG [main] .datasource.DataSourceTransactionManager (AbstractPlatformTransactionManager.java:851) - Initiating transaction rollback
2017-08-27T22:11:52,523 DEBUG [main] .datasource.DataSourceTransactionManager (DataSourceTransactionManager.java:325) - Rolling back JDBC transaction on Connection [com.mysql.jdbc.JDBC4Connection@9b367c8]
2017-08-27T22:11:52,527 DEBUG [main] .datasource.DataSourceTransactionManager (DataSourceTransactionManager.java:368) - Releasing JDBC Connection [com.mysql.jdbc.JDBC4Connection@9b367c8] after transaction
2017-08-27T22:11:52,527 DEBUG [main] ramework.jdbc.datasource.DataSourceUtils (DataSourceUtils.java:327) - Returning JDBC Connection to DataSource
2017-08-27T22:11:52,528 INFO  [main] t.context.transaction.TransactionContext (TransactionContext.java:136) - Rolled back transaction for test context [DefaultTestContext@62ea3440 testClass = BannerServiceImplTest, testInstance = com.yqg.loanmarket.service.impl.BannerServiceImplTest@3dddefd8, testMethod = testGetBannerListByStatus@BannerServiceImplTest, testException = java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.github.pagehelper.Page, mergedContextConfiguration = [MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]].
2017-08-27T22:11:52,529 DEBUG [main] tractDirtiesContextTestExecutionListener (AbstractDirtiesContextTestExecutionListener.java:106) - After test method: context [DefaultTestContext@62ea3440 testClass = BannerServiceImplTest, testInstance = com.yqg.loanmarket.service.impl.BannerServiceImplTest@3dddefd8, testMethod = testGetBannerListByStatus@BannerServiceImplTest, testException = java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.github.pagehelper.Page, mergedContextConfiguration = [MergedContextConfiguration@27953a83 testClass = BannerServiceImplTest, locations = '{}', classes = '{class com.yqg.loanmarket.MapperTestApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{classpath:application.properties}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@556d0826 key = [com.yqg.loanmarket.LoanMarketServiceConfiguration, org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration, org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration, org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration, org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, Package Import com.yqg.loanmarket.service.impl]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@37c7595, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@2dca0d64, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@351584c0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@ce1e4c33, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@22ffa91a], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].
`

**Comment by abnerbos** [comment]
不好意思，贴的日志可能有点混乱。。。。
我再看了下注解 @MybatisTest 会自动采用transactional然后rollback，不知道是否是由于这个导致PageHelper在单元测试中没有生效

**Comment by abel533** [comment]
估计是这个注解的机制没有用上分页插件。

**Comment by abnerbos** [comment]
嗯  org.mybatis.spring.boot.test.autoconfigure.MybatisTest 注解也是springboot中特有的，应该就是两者的兼容性问题了，我去学习下您的代码，看看能不能处理这个问题

**Comment by zhishengzhang** [comment]
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.github.pagehelper.Page

**Comment by zhishengzhang** [comment]
请问怎么回事

**Comment by abel533** [comment]
@zhishengzhang 查询结果没有经过分页。

只有真正通过PageHelper分页查询后的结果类型才是 `Page` ( `extends ArrayList`）。

**Comment by abnerbos** [comment]
补下之前遗留的问题吧，后面忙着项目，忘记这一茬了。后面找到问题所在的原因了，是由于我们这边单元测试里面没有打开EnableAutoConfiguration，所以需要手动@ImportAutoConfiguration(PageHelperAutoConfiguration.class)，不然PageInterceptor 无法配置成功，也就无法正常进行sql拦截并进行对应分页处理。

**Comment by CaiCao** [comment]
> 补下之前遗留的问题吧，后面忙着项目，忘记这一茬了。后面找到问题所在的原因了，是由于我们这边单元测试里面没有打开EnableAutoConfiguration，所以需要手动@ImportAutoConfiguration(PageHelperAutoConfiguration.class)，不然PageInterceptor 无法配置成功，也就无法正常进行sql拦截并进行对应分页处理。

请问转换异常的错误有解决了吗？这个是直接在测试类上加上@ImportAutoConfiguration(PageHelperAutoConfiguration.class)注解是吗？我加上这个注解后好像还是会报转换异常的错误

**Comment by bijibenhaha** [comment]
> 补下之前遗留的问题吧，后面忙着项目，忘记这一茬了。后面找到问题所在的原因了，是由于我们这边单元测试里面没有打开EnableAutoConfiguration，所以需要手动@ImportAutoConfiguration(PageHelperAutoConfiguration.class)，不然PageInterceptor 无法配置成功，也就无法正常进行sql拦截并进行对应分页处理。
这个方法可以用 太赞了 感谢

**Comment by bijibenhaha** [comment]
> > 补下之前遗留的问题吧，后面忙着项目，忘记这一茬了。后面找到问题所在的原因了，是由于我们这边单元测试里面没有打开EnableAutoConfiguration，所以需要手动@ImportAutoConfiguration(PageHelperAutoConfiguration.class)，不然PageInterceptor 无法配置成功，也就无法正常进行sql拦截并进行对应分页处理。
> 
> 请问转换异常的错误有解决了吗？这个是直接在测试类上加上@ImportAutoConfiguration(PageHelperAutoConfiguration.class)注解是吗？我加上这个注解后好像还是会报转换异常的错误

对的 可以解决问题
