### ISSUE TITLE
informix分页sql报错

### ISSUE THREAD

**Issue by damacheng009** [pagehelper/Mybatis-PageHelper#129]
PageHelper版本：5.1.2
informix版本：11.5

改成SELECT count(*) FROM t_customer则正常。

报错信息如下：
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.sql.SQLException: A syntax error has occurred.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy5.findAll(Unknown Source)
	at cn.itcast.dao.MybatisCustomerDaoImpl.findByPage(MybatisCustomerDaoImpl.java:108)

**Comment by abel533** [comment]
最新版本可以指定，count列，看这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/Changelog.md#501---2017-04-23

**Comment by damacheng009** [comment]
多谢，可以了。
还发现个小问题，就是如果不配置
<property name="helperDialect" value="informix"/>
就会报错：
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.github.pagehelper.PageException: 无法自动获取数据库类型，请通过 helperDialect 参数指定!
### Cause: com.github.pagehelper.PageException: 无法自动获取数据库类型，请通过 helperDialect 参数指定!
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy5.findAll(Unknown Source)
	at cn.itcast.dao.MybatisCustomerDaoImpl.findByPage(MybatisCustomerDaoImpl.java:108)

其他数据库不需要显示指定。

**Comment by damacheng009** [comment]
多谢，可以了。
还发现个小问题，就是如果不显式配置
helperDialect为informix就会报错：
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.github.pagehelper.PageException: 无法自动获取数据库类型，请通过 helperDialect 参数指定!
### Cause: com.github.pagehelper.PageException: 无法自动获取数据库类型，请通过 helperDialect 参数指定!
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy5.findAll(Unknown Source)
	at cn.itcast.dao.MybatisCustomerDaoImpl.findByPage(MybatisCustomerDaoImpl.java:108)

其他数据库不需要显示指定。

**Comment by abel533** [comment]
方便提供一下你们infomix的jdbcurl吗？（修改关键部分）。

**Comment by damacheng009** [comment]
jdbc:informix-sqli://localhost:9090/test:INFORMIXSERVER=xcc;IFX_USE_STRENC=true;CLIENT_LOCALE=EN_US.utf8;DB_LOCALE=EN_US.utf8;

**Comment by abel533** [comment]
找到原因了，默认根据`:informix-sqli:`这部分内容识别数据库，识别时没有`-sql`部分，所以没法自动识别。

informix 这部分有几种情况呢？

**Comment by damacheng009** [comment]
我也是第一次接触Informix，不过网上搜到的都是jdbc:informix-sqli开头的。

**Comment by abel533** [comment]
确实是这个，我后面加个映射关系。

**Comment by xueyuchen** [comment]
```java
accidentPage = PageHelper.startPage(1, 10).countColumn("id")
                    .doSelectPage(() -> this.accidentMapper.findUnGarageFinish(null, null, user.getRegionId(), 7));
```
为什么我这样写，countColumn不起作用呢？？
实际执行的sql还是
```sql
select count(0) from
```

**Comment by abel533** [comment]
@xueyuchen 单独开个issue吧。
