### ISSUE TITLE
动态sql语句查询分页sql报错

### ISSUE THREAD

**Issue by windy7829** [pagehelper/Mybatis-PageHelper#206]
使用分页插件做动态sql查询时，分页报错。
比如：
sql语句：select ${fields} from a
这里的${fields}是动态的字段。作为参数传入
在分页时
sql：select ${fields} from a limit ?
正确的应该是select ${fields} from a limit ?,?
加上分页时，limit后面变量少了一个，然后报错。
报错信息：
bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?
这是什么原因呢？
xml的sql语句：
<select id="queryA" resultType="java.util.LinkedHashMap" statementType="STATEMENT">
    select
    <foreach collection="fieldsList" index="index" item="fields" separator=",">
      ${fields}
    </foreach>
    from A a
</select>

**Comment by windy7829** [comment]
我debug了一下代码，发现动态的sql，字段为变量时(select ${fields} from a)，经过PageHelper解析，加上limit?,?之后，最后发往mybatis去执行时，不知道limit ?,?因何转变成了limit '?,?'。也就是把?,?当成了一个字符串，所以最终在数据库执行的sql就变成了select a,b,c,d from y limit '?,?'。
所以是不是可以理解PageHelper是在mybatis解析sql之前做的处理，而不是mybatis解析完往数据库执行时拦截再做解析，做分页，最后处理完最后发往数据库执行。
这个问题我尝试了很多次，只要用变量作为查询语句的字段，使用PageHelper分页就会出现这个错误。

**Comment by windy7829** [comment]
最后的异常信息为：
### SQL: select              pe_students.realname      ,        pe_students.username      ,        pe_students.phone      ,        pe_students.sex      ,        pe_students.email      ,        pe_students.qq      ,        pe_students.oldid           from pe_students pe_students LIMIT ?, ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?, ?' at line 17
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?, ?' at line 17
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:237)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy10.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy11.queryStudentsList(Unknown Source)

**Comment by abel533** [comment]
你使用的预编译方式吗？也就是 `statementType="PREPARED"`

**Comment by windy7829** [comment]
我使用的是非预编译方式。statementType="STATEMENT"

**Comment by abel533** [comment]
这里只能用预编译方式。

**Comment by windy7829** [comment]
那以后会支持非预编译方式吗？

**Comment by abel533** [comment]
目前没有计划。
