### ISSUE TITLE
jsqlparser-0.9.6及以上版本会异常，net.sf.jsqlparser.statement.select.Top类在0.9.6中有变更

### ISSUE THREAD

**Issue by galfordliu** [pagehelper/Mybatis-PageHelper#34]
Caused by: java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.Top.setRowCount(J)V
	at com.github.pagehelper.parser.SqlServerParser.<clinit>(SqlServerParser.java:77)
	at com.github.pagehelper.dialect.helper.SqlServerDialect.<init>(SqlServerDialect.java:44)
	at com.github.pagehelper.dialect.helper.SqlServer2012Dialect.<init>(SqlServer2012Dialect.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by abel533** [comment]
用指定版本。
