### ISSUE TITLE
5.1.8版本，自定义count查询后，单独调用有问题

### ISSUE THREAD

**Issue by shi-yuan** [pagehelper/Mybatis-PageHelper#344]
版本：5.1.8

配置：
```xml
<plugin interceptor="com.github.pagehelper.PageInterceptor">
    <property name="offsetAsPageNum" value="true"/>
    <property name="rowBoundsWithCount" value="true"/>
    <property name="pageSizeZero" value="true"/>
    <property name="reasonable" value="true"/>
    <property name="params" value="pageNum=start;pageSize=limit;"/>
</plugin>
```

使用场景：使用了手写的 count 查询，而且在接口中提供了相应的方法，例如
```xml
<select id="selectLeftjoin" resultType="com.github.pagehelper.model.Country">
    select a.id,b.countryname,a.countrycode from country a
    left join country b on a.id = b.id
    order by a.id
</select>
<select id="selectLeftjoin_COUNT" resultType="Long">
    select count(distinct a.id) from country a
    left join country b on a.id = b.id
</select>
```
现在直接调用手写的 count 查询，countryMapper.selectLeftjoin_COUNT，报异常：
````
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!
### Cause: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at sun.reflect.GeneratedMethodAccessor925.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	... 49 more
Caused by: java.lang.RuntimeException: 在系统中发现了多个分页插件，请检查系统配置!
	at com.github.pagehelper.PageHelper.skip(PageHelper.java:56)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:93)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy140.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 55 more
````

**Comment by abel533** [comment]
spring boot ? 用 starter 了？还用 xml 了？

**Comment by shi-yuan** [comment]
用的xml

**Comment by shi-yuan** [comment]
非spring boot

**Comment by abel533** [comment]
在 MyBatis 添加拦截器的方法上断点，看看何时配置的多个分页插件。

**Comment by shi-yuan** [comment]
![image](https://user-images.githubusercontent.com/8057153/58524505-027c8480-81fb-11e9-88ad-dde6ad325e44.png)

**Comment by shi-yuan** [comment]
这个判断是有问题的，现在调用的selectLeftjoin_COUNT，就是以_COUNT结尾，所以直接抛异常了

**Comment by abel533** [comment]
这是你自己手动调用的 selectLeftjoin_COUNT 方法吗？

**Comment by shi-yuan** [comment]
嗯，程序直接调用selectLeftjoin_COUNT

**Comment by shi-yuan** [comment]
目前的处理是
```java
PageHelper.count(() -> countryMapper.selectLeftjoin(...));
```

**Comment by abel533** [comment]
实际测试没有问题。

想要用 count 时，别自己调用 selectLeftjoin_COUNT，应该调用 selectLeftjoin，分页插件会自动找 selectLeftjoin_COUNT。

**Comment by shi-yuan** [comment]
ok，thx

**Comment by ghostman-git** [comment]
@abel533   有时候可能需要单独调用查询总数，  统计数量
