### ISSUE TITLE
Use PageHelper.startPage(Object params)  throw UnsupportedOperationException

### ISSUE THREAD

**Issue by HoyerIsAlexander** [pagehelper/Mybatis-PageHelper#365]
The error is 
java.lang.UnsupportedOperationException: null
at org.apache.ibatis.reflection.wrapper.CollectionWrapper.hasGetter(CollectionWrapper.java:78) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.reflection.MetaObject.hasGetter(MetaObject.java:109) ~[mybatis-3.4.6.jar:3.4.6]
	at pagehelper.util.PageObjectUtil.getParamValue(PageObjectUtil.java:161) ~[classes/:?]
	at pagehelper.util.PageObjectUtil.getPageFromObject(PageObjectUtil.java:106) ~[classes/:?]
	at das.pagehelper.page.PageMethod.startPage(PageMethod.java:85) ~[classes/:?]

mybatis:3.4.6
mybatis-spring:1.3.2
PageHelper:5.1.6

**Comment by abel533** [comment]
看问题似乎是你传入的参数是个集合？这里不支持。
