### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by 409036864** [pagehelper/Mybatis-PageHelper#376]
最新版的插件再使用mysql-connector-java 5.1.47会出现此问题，降低版本到5.1.32则不会出现此错误

Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at com.sun.proxy.$Proxy133.selectList(Unknown Source) ~[?:?]
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230) ~[mybatis-spring-2.0.1.jar:2.0.1]
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80) ~[mybatis-3.5.1.jar:3.5.1]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58) ~[mybatis-3.5.1.jar:3.5.1]
	at com.sun.proxy.$Proxy159.findList(Unknown Source) ~[?:?]

**Comment by 409036864** [comment]
返回了一个空的list 实际数据44条，查询返回0 并且部分查询总条数的又可以，部分不行

.connectionLog:132 - {conn-10005} pool-connect
2019-05-15 19:10:07.822 [http-nio-8001-exec-14] DEBUG org.mybatis.spring.transaction.SpringManagedTransaction=>org.mybatis.logging.Logger.debug:49 - JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@723c5f86] will not be managed by Spring
2019-05-15 19:10:07.828 [http-nio-8001-exec-14] DEBUG com.lc.module.dictionary.dao.DictionaryDao.findList_COUNT=>org.apache.ibatis.logging.jdbc.BaseJdbcLogger.debug:143 - ==> Preparing: SELECT count(0) FROM sys_dict
2019-05-15 19:10:07.833 [http-nio-8001-exec-14] DEBUG com.lc.module.dictionary.dao.DictionaryDao.findList_COUNT=>org.apache.ibatis.logging.jdbc.BaseJdbcLogger.debug:143 - ==> Parameters:
2019-05-15 19:10:07.837 [http-nio-8001-exec-14] DEBUG druid.sql.Statement=>com.alibaba.druid.filter.logging.Log4jFilter.statementLog:137 - {conn-10005, pstmt-20008} Parameters : []
2019-05-15 19:10:07.841 [http-nio-8001-exec-14] DEBUG druid.sql.Statement=>com.alibaba.druid.filter.logging.Log4jFilter.statementLog:137 - {conn-10005, pstmt-20008} Types : []
2019-05-15 19:10:07.895 [http-nio-8001-exec-14] DEBUG druid.sql.Statement=>com.alibaba.druid.filter.logging.Log4jFilter.statementLog:137 - {conn-10005, pstmt-20008} executed. 57.843765 millis. SELECT count(0) FROM sys_dict
2019-05-15 19:10:07.900 [http-nio-8001-exec-14] DEBUG druid.sql.ResultSet=>com.alibaba.druid.filter.logging.Log4jFilter.resultSetLog:142 - {conn-10005, pstmt-20008, rs-50012} open
2019-05-15 19:10:07.904 [http-nio-8001-exec-14] DEBUG druid.sql.ResultSet=>com.alibaba.druid.filter.logging.Log4jFilter.resultSetLog:142 - {conn-10005, pstmt-20008, rs-50012} Header: [count(0)]
2019-05-15 19:10:07.911 [http-nio-8001-exec-14] DEBUG com.lc.module.dictionary.dao.DictionaryDao.findList_COUNT=>org.apache.ibatis.logging.jdbc.BaseJdbcLogger.debug:143 - <== Total: 0
2019-05-15 19:10:07.915 [http-nio-8001-exec-14] DEBUG druid.sql.ResultSet=>com.alibaba.druid.filter.logging.Log4jFilter.resultSetLog:142 - {conn-10005, pstmt-20008, rs-50012} closed
2019-05-15 19:10:07.920 [http-nio-8001-exec-14] DEBUG druid.sql.Statement=>com.alibaba.druid.filter.logging.Log4jFilter.statementLog:137 - {conn-10005, pstmt-20008} clearParameters.

**Comment by abel533** [comment]
我目前用的 5.1.45 没有问题，没试过 47.
