### ISSUE TITLE
PageHelper 重写了自定义 sql ? 时而出现时而不出现。 

### ISSUE THREAD

**Issue by TianYongwei** [pagehelper/Mybatis-PageHelper#401]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

##  路过的大神帮忙看看，，，多谢

> 说明：很奇怪遇见这个问题，前几天还遇见个问题，会在 一个单条查询 方法上添加分页 limit 10, 10 .这样直接导致查不到数据，然后重建用户信息，然后用户信息重复报错。
不知道是不是跟 PageHelper 有关系，那里用的不对吗？

### 使用环境

* PageHelper 版本: 5.1.2
* 数据库类型和版本: mysql 5.7
* JDBC_URL: jdbc.url=jdbc\:mysql\://ip_address\:3306/gooniecat-test?useUnicode\=true&characterEncoding\=UTF-8&zeroDateTimeBehavior\=convertToNull

### mybatis 配置

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN" "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
	<!--配置全局属性 -->
	<settings>
		<!--使用jdbc的getGeneratekeys获取自增主键值 -->
		<setting name="useGeneratedKeys" value="true" />
		<!--使用列别名替换别名 默认true -->
		<setting name="useColumnLabel" value="true" />
		<!--开启驼峰命名转换Table:create_time到 Entity(createTime) -->
		<setting name="mapUnderscoreToCamelCase" value="true" />
		<setting name="logImpl" value="STDOUT_LOGGING" />
	</settings>
	<plugins>
	<!-- 5.1.1 -->
		<plugin interceptor="com.github.pagehelper.PageInterceptor">
			<property name="offsetAsPageNum" value="false" />
			<property name="rowBoundsWithCount" value="false" />
			<property name="pageSizeZero" value="true" />
			<property name="reasonable" value="false" />
			<property name="supportMethodsArguments" value="false" />
			<property name="returnPageInfo" value="none" />
		</plugin>
	</plugins>
</configuration>
```

### SQL 解析错误

serviceImpl.java

```java
@Override
	public BizProduct selectByPrimaryKey(Long id) {
		// 下面一行时而报错
		BizProduct obj=bizProductMapper.selectByPrimaryKey(id);
		obj.setProductdescription(StrUtils.charsspecialhtml(obj.getProductdescription()));
		obj.setBrownum(obj.getBrownum()+1);//修改浏览量
                 bizProductMapper.updateByPrimaryKeySelective(obj);
		return obj;
	}
```

mapper.java

```java
BizProduct selectByPrimaryKey(Long id);
```

mapper.xml

```xml
<select id="selectByPrimaryKey" parameterType="java.lang.Long" resultMap="BaseResultMap">
    SELECT
    c.*,
    s.id AS sid,
    s.*,
    au.shopname as suppliershopname,
    au.photos as supplierphotos,
    ps.id as psid,
    ps.SELLNUM as SSELLNUM,
    ps.STOCK as SSTOCK,
    ps.createTime as screateTime,
    ps.delId as sdelId,
    ps.*
    FROM
    biz_product c
    LEFT JOIN biz_product_affix s ON c.id = s.CID
    LEFT JOIN biz_product_specifications ps on ps.PRODUCTID=c.id
    LEFT JOIN aclusers au on au.id = c.supplier

    where c.id = #{id} AND ps.DELID = 1
    order by s.orderby desc
  </select>
```

```

#### 期望的结果：

```sql
SELECT c.*, s.id AS sid, s.*, au.shopname as suppliershopname, au.photos as supplierphotos, ps.id as psid, ps.SELLNUM as SSELLNUM, ps.STOCK as SSTOCK, ps.createTime as screateTime, ps.delId as sdelId, ps.* FROM biz_product c 
LEFT JOIN biz_product_affix s ON c.id = s.CID 
LEFT JOIN biz_product_specifications ps on ps.PRODUCTID=c.id 
LEFT JOIN aclusers au on au.id = c.supplier 
where c.id = ? AND ps.DELID = 1 order by s.orderby desc
```

### 完整异常信息

```
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@43aba47c] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@2ffb3c5f] will not be managed by Spring
==>  Preparing: SELECT count(0) FROM biz_product c LEFT JOIN biz_product_affix s ON c.id = s.CID LEFT JOIN biz_product_specifications ps ON ps.PRODUCTID = c.id LEFT JOIN aclusers au ON au.id = c.supplier WHERE c.id = ? AND ps.DELID = 1 
==> Parameters: 1578(Long)
<==    Columns: count(0)
<==        Row: 2
<==      Total: 1
==>  Preparing: SELECT c.*, s.id AS sid, s.*, au.shopname AS suppliershopname, au.photos AS supplierphotos, ps.id AS psid, ps.SELLNUM AS SSELLNUM, ps.STOCK AS SSTOCK, ps.createTime AS screateTime, ps.delId AS sdelId, ps.* FROM biz_product c LEFT JOIN biz_product_affix s ON c.id = s.CID LEFT JOIN biz_product_specifications ps ON ps.PRODUCTID = c.id LEFT JOIN aclusers au ON au.id = c.supplier WHERE c.id = ? AND ps.DELID = 1 order by id desc LIMIT ? 
==> Parameters: 1578(Long), 10(Integer)
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@43aba47c]
2019-06-15 11:26:12 [ERROR] - com.taobao.exception.GlobalExceptionResolver -GlobalExceptionResolver.java(26) -访问/gooniesys/index/detail/1578 发生错误, 错误信息:
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
### The error may exist in file [/usr/local/tomcat3/webapps/gooniesys/WEB-INF/classes/com/taobao/mapping/shop/BizProductMapper.xml]
### The error may involve com.taobao.dao.shop.BizProductMapper.selectByPrimaryKey-Inline
### The error occurred while setting parameters
### SQL: SELECT c.*, s.id AS sid, s.*, au.shopname AS suppliershopname, au.photos AS supplierphotos, ps.id AS psid, ps.SELLNUM AS SSELLNUM, ps.STOCK AS SSTOCK, ps.createTime AS screateTime, ps.delId AS sdelId, ps.* FROM biz_product c LEFT JOIN biz_product_affix s ON c.id = s.CID LEFT JOIN biz_product_specifications ps ON ps.PRODUCTID = c.id LEFT JOIN aclusers au ON au.id = c.supplier WHERE c.id = ? AND ps.DELID = 1 order by id desc LIMIT ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
; SQL []; Column 'id' in order clause is ambiguous; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
org.springframework.dao.DataIntegrityViolationException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
### The error may exist in file [/usr/local/tomcat3/webapps/gooniesys/WEB-INF/classes/com/taobao/mapping/shop/BizProductMapper.xml]
### The error may involve com.taobao.dao.shop.BizProductMapper.selectByPrimaryKey-Inline
### The error occurred while setting parameters
### SQL: SELECT c.*, s.id AS sid, s.*, au.shopname AS suppliershopname, au.photos AS supplierphotos, ps.id AS psid, ps.SELLNUM AS SSELLNUM, ps.STOCK AS SSTOCK, ps.createTime AS screateTime, ps.delId AS sdelId, ps.* FROM biz_product c LEFT JOIN biz_product_affix s ON c.id = s.CID LEFT JOIN biz_product_specifications ps ON ps.PRODUCTID = c.id LEFT JOIN aclusers au ON au.id = c.supplier WHERE c.id = ? AND ps.DELID = 1 order by id desc LIMIT ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
; SQL []; Column 'id' in order clause is ambiguous; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:86)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy21.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:163)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy22.selectByPrimaryKey(Unknown Source)
	at com.taobao.service.shop.impl.ProductServiceImpl.selectByPrimaryKey(ProductServiceImpl.java:279)
	at sun.reflect.GeneratedMethodAccessor910.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy38.selectByPrimaryKey(Unknown Source)
	at com.taobao.controller.shop.IndexController.productDetail(IndexController.java:176)
	at sun.reflect.GeneratedMethodAccessor909.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:690)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:876)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.ctkj.acl.filter.HyLoginFilter.doFilter(HyLoginFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'id' in order clause is ambiguous
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
	at com.mysql.jdbc.Util.getInstance(Util.java:384)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4232)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1307)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.wall.WallFilter.preparedStatement_execute(WallFilter.java:600)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:62)
	at com.sun.proxy.$Proxy118.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:59)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:136)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:60)
	at com.sun.proxy.$Proxy116.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	... 68 more

```

**Comment by abel533** [comment]
建议先升级到最新版本。

然后看这里：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md#3-pagehelper-%E5%AE%89%E5%85%A8%E8%B0%83%E7%94%A8

**Comment by TianYongwei** [comment]
@abel533 感谢回复。
但是我又想到了一个问题，其实我这个 `selectByPrimarykey` 方法根本不需要分页啊 ？

**Comment by abel533** [comment]
上面链接看了吗？

**Comment by TianYongwei** [comment]
能讲下具体哪块吗？
我在全部使用 pagehelper的地方使用 try - finally 进行 `PageHelper.clearPage(); `吗

**Comment by abel533** [comment]
不用，不推荐手动 clearPage。

看这部分**4. 什么时候会导致不安全的分页？**

**Comment by TianYongwei** [comment]
项目里很有可能存在不安全的分页 ，声明了 ，但是使用之前异常了。

一个个检查使用pagehelper地方的逻辑？哎 累啊

**Comment by abel533** [comment]
如果所有人不能统一按照规范写。。。可以优先考虑 PageRowbounds，其次 clearPage
