### ISSUE TITLE
NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()

### ISSUE THREAD

**Issue by MrHeXi** [pagehelper/Mybatis-PageHelper#407]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 异常模板
Caused by: java.lang.NoSuchMethodError: net.sf.jsqlparser.statement.select.PlainSelect.getGroupByColumnReferences()Ljava/util/List;
	at com.github.pagehelper.parser.CountSqlParser.isSimpleCount(CountSqlParser.java:156)
	at com.github.pagehelper.parser.CountSqlParser.sqlToCount(CountSqlParser.java:135)
	at com.github.pagehelper.parser.CountSqlParser.getSmartCountSql(CountSqlParser.java:94)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getCountSql(AbstractHelperDialect.java:81)
	at com.github.pagehelper.PageHelper.getCountSql(PageHelper.java:77)
	at com.github.pagehelper.PageInterceptor.executeAutoCount(PageInterceptor.java:193)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:113)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy297.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy177.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy226.selectByExample(Unknown Source)
### 使用环境

* PageHelper 版本: 5.1.2
* 数据库类型和版本: mysql 7.0
*JSqlParser:2.0

JSqlParser 2.0以上删除getGroupByColumnReferences这个方法，PageHelper有计划升级对应的方法吗

**Comment by abel533** [comment]
用和分页插件匹配的版本。。

最新版本用 2.0

**Comment by zhengyuzh** [comment]
版本退回 1.4 这个可以解决。
 <dependency>
            <groupId>com.github.jsqlparser</groupId>
            <artifactId>jsqlparser</artifactId>
            <version>1.4</version>
        </dependency>
