### ISSUE TITLE
v4.2项目启动时，并发访问会报空指针

### ISSUE THREAD

**Issue by 4umine** [pagehelper/Mybatis-PageHelper#422]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

## 问题描述

项目启动后，并发访问会出现空指针，如下

```java
Caused by: java.lang.NullPointerException: null
	at com.github.pagehelper.util.SqlUtil.doIntercept(SqlUtil.java:120) ~[pagehelper-4.2.1.jar:na]
	at com.github.pagehelper.util.SqlUtil.intercept(SqlUtil.java:84) ~[pagehelper-4.2.1.jar:na]
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:50) ~[pagehelper-4.2.1.jar:na]
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.0.jar:3.4.0]
	at com.sun.proxy.$Proxy189.query(Unknown Source) ~[na:na]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.0.jar:3.4.0]
	... 103 common frames omitted
```

## 代码

`SqlUtil`类 doIntercept( )方法
```java
        if(autoDialect){
            lock.lock();
            try{
                if(autoDialect){
                    // 1、这里将autoDialect 改为false，如果此时变量刷回主存，
                   // dialect 还是 null
                    autoDialect = false;
                    this.dialect = getDialect(ms);
                }
            }finally {
                lock.unlock();
            }
        }
        // 2、这里runtimeDialect = null
        Dialect runtimeDialect = dialect;

        // 3、这里将会报NPE
        if (!runtimeDialect.skip(ms, parameterObject, rowBounds)) {
        }
```

## 修改

修改如下：

- 将autoDialect 用 volatile 修饰

```java
//自动获取dialect,如果没有setProperties或setSqlUtilConfig，也可以正常进行
private volatile boolean autoDialect = true;
```

- 先初始化 dialect，再改变autoDialect的值

```java
        if(autoDialect){
            lock.lock();
            try{
                if(autoDialect){
                    // 这里顺序换下
                    this.dialect = getDialect(ms);
                    autoDialect = false;
                }
            }finally {
                lock.unlock();
            }
        }
```

这样能保证其它线程看到 autoDialect = false 的时候，dialect 已经初始化完成。

**Comment by gaowenbo** [comment]
me too

**Comment by 4umine** [comment]
> me too

**Comment by 4umine** [comment]
> me too

可以试着按我的方法解决掉这个问题
