### ISSUE TITLE
informix4.10查询报错

### ISSUE THREAD

**Issue by djshangqwe** [pagehelper/Mybatis-PageHelper#441]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.2
* 数据库类型和版本: informix4.10.6
* JDBC_URL: jdbc:informix-sqli::informixserver=dbserver;NEWLOCALE=zh_CN,en_us;NEWCODESET=gbk,8859-1,819;IFX_LOCK_MODE_WAIT=10

#### 分页参数

```java
PageHelper.startPage(1, 10);
corpOperatorMapper.findRingProducer("6");
```

#### 原 SQL

```sql
select operatorid as ringproducerid, username as ringproducername, operatorname as ringmaker, mobile as phonenumber,email
    from mrbt_corpoperator where oplevel=#{oplevel}
```

### 完整异常信息
 Error querying database.  Cause: java.sql.SQLException: Type not supported
 The error may exist in file [D:\business\Java_jar\tomcat_8.5\apache-tomcat-8.5.43\wtpwebapps\mrbt-corp-webapp\WEB-INF\classes\mapping\CorpOperatorMapper.xml]
 The error may involve defaultParameterMap
The error occurred while setting parameters
 SQL: SELECT  SKIP ?  FIRST ?  * FROM ( select operatorid as ringproducerid, username as ringproducername, operatorname as ringmaker, mobile as phonenumber,email     from mrbt_corpoperator where oplevel=? ) TEMP_T
### Cause: java.sql.SQLException: Type not supported
; uncategorized SQLException for SQL []; SQL state [IX000]; error code [-79714]; Type not supported; nested exception is java.sql.SQLException: Type not supported
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
```
异常信息放在这里
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by fangjinuo** [comment]
试试这个 [sqlhelper](https://github.com/fangjinuo/sqlhelper)

**Comment by abel533** [comment]
和你xml的statementType有关
