### ISSUE TITLE
SQLSERVER的复杂SQL查询出现异常“不支持该SQL转换为分页查询!”估计是jsqlparser对with(nolock)的支持还不够好

### ISSUE THREAD

**Issue by KIDXT** [pagehelper/Mybatis-PageHelper#448]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

问题描述：
SQLSERVER的复杂SQL查询，如果不用PageHelper分页，是能正常获取到结果的。
用PageHelper后，出现异常，信息为：“不支持该SQL转换为分页查询!”
原因是由于net.sf.jsqlparser.parser.CCJSqlParserUtil.parse函数引起的
jsqlparser的版本已经升级到2.0，但对于with (nolock)语句的解析还不够好。
如果把所有with (nolock)去掉，就能正常获取到结果。

### 使用环境

* PageHelper 版本: 5.1.10
* 数据库类型和版本: SQLSERVER 2012
* JDBC_URL: xxx

#### 分页参数
PageHelper.startPage(0,1);

#### 原 SQL

```sql
SELECT
  计划生产.编号 , 
  计划生产.投产号 ,
  铸件作业路线.作业顺序 ,铸件作业路线.工序号,
  铸件作业路线.作业工序  AS 作业工序,
  铸件作业路线.作业工序  AS 作业描述, 
  V计划质检.工废数 ,
  V计划质检.料废数 ,
  V计划质检.回用数 ,
  V计划质检.合格数 + ISNULL(V计划质检.虚拟合格数,0) AS 合格数 ,
  V计划质检.虚拟合格数 ,
  V计划质检.操作人 ,
  V计划质检.检验员 ,
  V计划质检.报工日期 ,
  V计划质检.回用说明 ,
  V计划质检.工废说明 ,
  V计划质检.料废说明 ,
  V计划质检.备注 ,
  V计划质检.委外单号 ,
	订单细则.对应工艺单号,
	V计划质检.质量等级1,
	NULL 工艺原件,NULL 工艺备注
  
FROM
  计划生产 WITH ( NOLOCK )
  LEFT OUTER JOIN 计划投产 WITH ( NOLOCK ) ON 计划投产.投产号 = 计划生产.投产号
  LEFT OUTER JOIN 
	(
	SELECT  序号, 路线模板名称, 作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 备注, 前期等待时间, 操作时间, 
									后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,流卡号
	FROM  铸件作业路线流程卡  铸件作业路线2
	WHERE 铸件作业路线2.自定义模板=1 
	
UNION ALL
		SELECT  序号, 铸件作业路线3.细则号, 铸件作业路线3.作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 铸件作业路线3.备注, 前期等待时间, 操作时间, 
									后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,计划生产.编号
	FROM  铸件作业路线  铸件作业路线3
	LEFT OUTER JOIN 计划投产 ON  铸件作业路线3.细则号 = 计划投产.路线方案 
	LEFT OUTER JOIN 计划生产 ON 计划生产.投产号=计划投产.投产号

WHERE 计划投产.投产号<250  AND  计划投产.投产号  NOT IN ('87','66','111','213','160','118','156','59','112','72','141','127') 
	AND 计划生产.制表日期<'2019-07-30' OR (计划投产.投产号=307 AND 铸件作业路线3.作业顺序>55)
	UNION ALL
	SELECT NULL, V路线.细则号, 1000+V.顺序, NULL, NULL, NULL, 1, NULL, NULL, NULL,NULL, NULL, NULL, NULL, NULL,NULL 
	FROM
	(
	SELECT   TOP 20 ROW_NUMBER() OVER (ORDER BY  职工编号 )  顺序
	FROM     职工信息 WITH(NOLOCK)
		) V,
	(SELECT  细则号,COUNT(*) 行数 FROM 铸件作业路线 WHERE 自定义模板=1 GROUP BY 细则号) V路线 
	WHERE V.顺序 > V路线.行数  
	)铸件作业路线  
	ON 计划生产.编号 = 铸件作业路线.流卡号

	  LEFT OUTER JOIN 订单细则 WITH ( NOLOCK ) ON 订单细则.订单细则号 = 计划投产.细则号 
  LEFT OUTER JOIN (
	  SELECT 投产号,补加,前道计划编号,作业顺序,
	  SUM ( V计划质检.工废数 ) AS 工废数 ,
	  SUM ( V计划质检.料废数 ) AS 料废数 ,
	  SUM ( V计划质检.回用数 ) AS 回用数 ,
	  SUM ( V计划质检.合格数 ) AS 合格数 ,
	  SUM ( V计划质检.虚拟合格数 ) AS 虚拟合格数 ,
	  CASE WHEN COUNT (DISTINCT V计划质检.质量等级)>1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.质量等级 ) ) ) + '等级' ELSE MAX ( V计划质检.质量等级 ) END AS 质量等级1 ,
	  CASE WHEN COUNT ( DISTINCT V计划质检.操作人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.操作人 ) ) ) + '个人' ELSE MAX ( V计划质检.操作人 ) END AS 操作人 ,
	  CASE WHEN COUNT ( DISTINCT V计划质检.检验人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.检验人 ) ) ) + '个人' ELSE MAX ( V计划质检.检验人 ) END AS 检验员 ,
	  MAX ( V计划质检.制表日期 ) AS 报工日期 ,
	  CASE WHEN COUNT ( DISTINCT V计划质检.回用说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.回用说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.回用说明 ) END AS 回用说明 ,
	  CASE WHEN COUNT ( DISTINCT V计划质检.工废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.工废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.工废说明 ) END AS 工废说明 ,
	   CASE WHEN COUNT ( DISTINCT V计划质检.料废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.料废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.料废说明 ) END AS 料废说明 ,
	  (CASE 
		WHEN V计划质检.工序 IN ('熔炼','熔炼浇注','时效')
		THEN
		(CASE WHEN COUNT(DISTINCT V计划质检.批次号 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.批次号 ) ) ) + '炉;' ELSE '炉号'+LTRIM(RTRIM(MAX ( V计划质检.批次号 )))+';' END)
		ELSE '' END
		)
		+MAX ( ISNULL ( V计划质检.备注 , '' ) ) AS 备注,
	  MAX ( V计划质检.委外单号 ) AS 委外单号
	  FROM
	  (
		 SELECT
		  编号 ,  验收时间 制表日期 ,  工序 ,  工废数 ,  料废数 ,
		  合格数 ,  回用数 , 0 虚拟合格数 ,料废说明,
		  操作人 ,
		  检验人 ,  回用说明 ,	 
		  工废说明 ,
		  验收点评 AS 备注 ,
		  作业顺序 ,  投产号 ,  补加 ,
		  NULL AS 委外单号 ,
		  CASE WHEN 工序='加工' THEN 前道计划编号 ELSE 编号 END AS 前道计划编号,批次号,质量等级
		FROM
		  计划生产 AS 计划生产_1  WITH ( NOLOCK )
	  UNION ALL 
		SELECT
		  编号 ,  制表日期 ,  工序 ,  工废数 ,  料废数 ,
		  合格数 ,  回用数 , 虚拟合格数 , 料废说明, 操作人 ,  检验人 ,
		  回用说明 ,  工废说明 ,  备注 ,  作业顺序 ,  投产号 ,
		  补加 ,  委外单号 ,  前道计划编号,批次号,质量等级
		FROM
		  质检批量   WITH ( NOLOCK )
	  )  V计划质检
	  GROUP BY 投产号,补加,前道计划编号,作业顺序,工序


) AS V计划质检 ON V计划质检.作业顺序 = 铸件作业路线.作业顺序
   AND V计划质检.投产号 = 计划投产.投产号
  AND V计划质检.补加 = 计划生产.补加
  AND V计划质检.前道计划编号=计划生产.编号
  LEFT OUTER JOIN (
  SELECT
    路线模板名称,
   MAX ( 作业顺序 ) AS 作业顺序
  FROM
    铸件作业路线流程卡 AS 铸件作业路线_1 WITH ( NOLOCK )
  WHERE
    ( 自定义模板 = 1 ) AND
     ( 作业工序 IN ( '打磨','任务下达' ) )
  GROUP  BY
    路线模板名称
) AS V路线熔炼顺序 ON V路线熔炼顺序.路线模板名称 = 计划投产.路线方案
```

### 完整异常信息
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(0) from ( SELECT   计划生产.编号 ,    计划生产.投产号 ,   铸件作业路线.作业顺序 ,铸件作业路线.工序号,   铸件作业路线.作业工序  AS 作业工序,   铸件作业路线.作业工序  AS 作业描述,    V计划质检.工废数 ,   V计划质检.料废数 ,   V计划质检.回用数 ,   V计划质检.合格数 + ISNULL(V计划质检.虚拟合格数,0) AS 合格数 ,   V计划质检.虚拟合格数 ,   V计划质检.操作人 ,   V计划质检.检验员 ,   V计划质检.报工日期 ,   V计划质检.回用说明 ,   V计划质检.工废说明 ,   V计划质检.料废说明 ,   V计划质检.备注 ,   V计划质检.委外单号 ,  订单细则.对应工艺单号,  V计划质检.质量等级1,  NULL 工艺原件,NULL 工艺备注    FROM   计划生产 WITH ( NOLOCK )   LEFT OUTER JOIN 计划投产 WITH ( NOLOCK ) ON 计划投产.投产号 = 计划生产.投产号   LEFT OUTER JOIN   (  SELECT  序号, 路线模板名称, 作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 备注, 前期等待时间, 操作时间,           后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,流卡号  FROM  铸件作业路线流程卡  铸件作业路线2  WHERE 铸件作业路线2.自定义模板=1    UNION ALL   SELECT  序号, 铸件作业路线3.细则号, 铸件作业路线3.作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 铸件作业路线3.备注, 前期等待时间, 操作时间,           后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,计划生产.编号  FROM  铸件作业路线  铸件作业路线3  LEFT OUTER JOIN 计划投产 ON  铸件作业路线3.细则号 = 计划投产.路线方案   LEFT OUTER JOIN 计划生产 ON 计划生产.投产号=计划投产.投产号  WHERE 计划投产.投产号<250  AND  计划投产.投产号  NOT IN ('87','66','111','213','160','118','156','59','112','72','141','127')   AND 计划生产.制表日期<'2019-07-30' OR (计划投产.投产号=307 AND 铸件作业路线3.作业顺序>55)  UNION ALL  SELECT NULL, V路线.细则号, 1000+V.顺序, NULL, NULL, NULL, 1, NULL, NULL, NULL,NULL, NULL, NULL, NULL, NULL,NULL   FROM  (  SELECT   TOP 20 ROW_NUMBER() OVER (ORDER BY  职工编号 )  顺序  FROM     职工信息 WITH(NOLOCK)   ) V,  (SELECT  细则号,COUNT(*) 行数 FROM 铸件作业路线 WHERE 自定义模板=1 GROUP BY 细则号) V路线   WHERE V.顺序 > V路线.行数    )铸件作业路线    ON 计划生产.编号 = 铸件作业路线.流卡号     LEFT OUTER JOIN 订单细则 WITH ( NOLOCK ) ON 订单细则.订单细则号 = 计划投产.细则号    LEFT OUTER JOIN (    SELECT 投产号,补加,前道计划编号,作业顺序,    SUM ( V计划质检.工废数 ) AS 工废数 ,    SUM ( V计划质检.料废数 ) AS 料废数 ,    SUM ( V计划质检.回用数 ) AS 回用数 ,    SUM ( V计划质检.合格数 ) AS 合格数 ,    SUM ( V计划质检.虚拟合格数 ) AS 虚拟合格数 ,    CASE WHEN COUNT (DISTINCT V计划质检.质量等级)>1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.质量等级 ) ) ) + '等级' ELSE MAX ( V计划质检.质量等级 ) END AS 质量等级1 ,    CASE WHEN COUNT ( DISTINCT V计划质检.操作人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.操作人 ) ) ) + '个人' ELSE MAX ( V计划质检.操作人 ) END AS 操作人 ,    CASE WHEN COUNT ( DISTINCT V计划质检.检验人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.检验人 ) ) ) + '个人' ELSE MAX ( V计划质检.检验人 ) END AS 检验员 ,    MAX ( V计划质检.制表日期 ) AS 报工日期 ,    CASE WHEN COUNT ( DISTINCT V计划质检.回用说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.回用说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.回用说明 ) END AS 回用说明 ,    CASE WHEN COUNT ( DISTINCT V计划质检.工废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.工废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.工废说明 ) END AS 工废说明 ,     CASE WHEN COUNT ( DISTINCT V计划质检.料废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.料废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.料废说明 ) END AS 料废说明 ,    (CASE    WHEN V计划质检.工序 IN ('熔炼','熔炼浇注','时效')   THEN   (CASE WHEN COUNT(DISTINCT V计划质检.批次号 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.批次号 ) ) ) + '炉;' ELSE '炉号'+LTRIM(RTRIM(MAX ( V计划质检.批次号 )))+';' END)   ELSE '' END   )   +MAX ( ISNULL ( V计划质检.备注 , '' ) ) AS 备注,    MAX ( V计划质检.委外单号 ) AS 委外单号    FROM    (    SELECT     编号 ,  验收时间 制表日期 ,  工序 ,  工废数 ,  料废数 ,     合格数 ,  回用数 , 0 虚拟合格数 ,料废说明,     操作人 ,     检验人 ,  回用说明 ,       工废说明 ,     验收点评 AS 备注 ,     作业顺序 ,  投产号 ,  补加 ,     NULL AS 委外单号 ,     CASE WHEN 工序='加工' THEN 前道计划编号 ELSE 编号 END AS 前道计划编号,批次号,质量等级   FROM     计划生产 AS 计划生产_1  WITH ( NOLOCK )    UNION ALL    SELECT     编号 ,  制表日期 ,  工序 ,  工废数 ,  料废数 ,     合格数 ,  回用数 , 虚拟合格数 , 料废说明, 操作人 ,  检验人 ,     回用说明 ,  工废说明 ,  备注 ,  作业顺序 ,  投产号 ,     补加 ,  委外单号 ,  前道计划编号,批次号,质量等级   FROM     质检批量   WITH ( NOLOCK )    )  V计划质检    GROUP BY 投产号,补加,前道计划编号,作业顺序,工序   ) AS V计划质检 ON V计划质检.作业顺序 = 铸件作业路线.作业顺序    AND V计划质检.投产号 = 计划投产.投产号   AND V计划质检.补加 = 计划生产.补加   AND V计划质检.前道计划编号=计划生产.编号   LEFT OUTER JOIN (   SELECT     路线模板名称,    MAX ( 作业顺序 ) AS 作业顺序   FROM     铸件作业路线流程卡 AS 铸件作业路线_1 WITH ( NOLOCK )   WHERE     ( 自定义模板 = 1 ) AND      ( 作业工序 IN ( '打磨','任务下达' ) )   GROUP  BY     路线模板名称 ) AS V路线熔炼顺序 ON V路线熔炼顺序.路线模板名称 = 计划投产.路线方案 ) tmp_count
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy96.selectCursor(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectCursor(SqlSessionTemplate.java:206)
	at org.apache.ibatis.binding.MapperMethod.executeForCursor(MapperMethod.java:159)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy148.selectJoinTableDataFromTableWithSearch(Unknown Source)
	at com.ruoyi.module.service.DatabaseCommonService.selectJoinTableList(DatabaseCommonService.java:535)
	at com.ruoyi.module.service.DatabaseCommonService$$FastClassBySpringCGLIB$$ab8b9093.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.ruoyi.module.service.DatabaseCommonService$$EnhancerBySpringCGLIB$$e8087923.selectJoinTableList(<generated>)
	at com.ruoyi.test.RuoYiApplicationTest.testComplexSQL(RuoYiApplicationTest.java:394)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(0) from ( SELECT   计划生产.编号 ,    计划生产.投产号 ,   铸件作业路线.作业顺序 ,铸件作业路线.工序号,   铸件作业路线.作业工序  AS 作业工序,   铸件作业路线.作业工序  AS 作业描述,    V计划质检.工废数 ,   V计划质检.料废数 ,   V计划质检.回用数 ,   V计划质检.合格数 + ISNULL(V计划质检.虚拟合格数,0) AS 合格数 ,   V计划质检.虚拟合格数 ,   V计划质检.操作人 ,   V计划质检.检验员 ,   V计划质检.报工日期 ,   V计划质检.回用说明 ,   V计划质检.工废说明 ,   V计划质检.料废说明 ,   V计划质检.备注 ,   V计划质检.委外单号 ,  订单细则.对应工艺单号,  V计划质检.质量等级1,  NULL 工艺原件,NULL 工艺备注    FROM   计划生产 WITH ( NOLOCK )   LEFT OUTER JOIN 计划投产 WITH ( NOLOCK ) ON 计划投产.投产号 = 计划生产.投产号   LEFT OUTER JOIN   (  SELECT  序号, 路线模板名称, 作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 备注, 前期等待时间, 操作时间,           后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,流卡号  FROM  铸件作业路线流程卡  铸件作业路线2  WHERE 铸件作业路线2.自定义模板=1    UNION ALL   SELECT  序号, 铸件作业路线3.细则号, 铸件作业路线3.作业顺序, 作业工序, 作业描述, 计划耗时, 自定义模板, 铸件作业路线3.备注, 前期等待时间, 操作时间,           后期等待时间,NULL  关键工序, 工序号, 特殊工序标记, 工艺备注,计划生产.编号  FROM  铸件作业路线  铸件作业路线3  LEFT OUTER JOIN 计划投产 ON  铸件作业路线3.细则号 = 计划投产.路线方案   LEFT OUTER JOIN 计划生产 ON 计划生产.投产号=计划投产.投产号  WHERE 计划投产.投产号<250  AND  计划投产.投产号  NOT IN ('87','66','111','213','160','118','156','59','112','72','141','127')   AND 计划生产.制表日期<'2019-07-30' OR (计划投产.投产号=307 AND 铸件作业路线3.作业顺序>55)  UNION ALL  SELECT NULL, V路线.细则号, 1000+V.顺序, NULL, NULL, NULL, 1, NULL, NULL, NULL,NULL, NULL, NULL, NULL, NULL,NULL   FROM  (  SELECT   TOP 20 ROW_NUMBER() OVER (ORDER BY  职工编号 )  顺序  FROM     职工信息 WITH(NOLOCK)   ) V,  (SELECT  细则号,COUNT(*) 行数 FROM 铸件作业路线 WHERE 自定义模板=1 GROUP BY 细则号) V路线   WHERE V.顺序 > V路线.行数    )铸件作业路线    ON 计划生产.编号 = 铸件作业路线.流卡号     LEFT OUTER JOIN 订单细则 WITH ( NOLOCK ) ON 订单细则.订单细则号 = 计划投产.细则号    LEFT OUTER JOIN (    SELECT 投产号,补加,前道计划编号,作业顺序,    SUM ( V计划质检.工废数 ) AS 工废数 ,    SUM ( V计划质检.料废数 ) AS 料废数 ,    SUM ( V计划质检.回用数 ) AS 回用数 ,    SUM ( V计划质检.合格数 ) AS 合格数 ,    SUM ( V计划质检.虚拟合格数 ) AS 虚拟合格数 ,    CASE WHEN COUNT (DISTINCT V计划质检.质量等级)>1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.质量等级 ) ) ) + '等级' ELSE MAX ( V计划质检.质量等级 ) END AS 质量等级1 ,    CASE WHEN COUNT ( DISTINCT V计划质检.操作人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.操作人 ) ) ) + '个人' ELSE MAX ( V计划质检.操作人 ) END AS 操作人 ,    CASE WHEN COUNT ( DISTINCT V计划质检.检验人 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.检验人 ) ) ) + '个人' ELSE MAX ( V计划质检.检验人 ) END AS 检验员 ,    MAX ( V计划质检.制表日期 ) AS 报工日期 ,    CASE WHEN COUNT ( DISTINCT V计划质检.回用说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.回用说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.回用说明 ) END AS 回用说明 ,    CASE WHEN COUNT ( DISTINCT V计划质检.工废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.工废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.工废说明 ) END AS 工废说明 ,     CASE WHEN COUNT ( DISTINCT V计划质检.料废说明 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.料废说明 ) ) ) + '个原因' ELSE MAX ( V计划质检.料废说明 ) END AS 料废说明 ,    (CASE    WHEN V计划质检.工序 IN ('熔炼','熔炼浇注','时效')   THEN   (CASE WHEN COUNT(DISTINCT V计划质检.批次号 ) > 1 THEN LTRIM ( RTRIM ( COUNT ( DISTINCT V计划质检.批次号 ) ) ) + '炉;' ELSE '炉号'+LTRIM(RTRIM(MAX ( V计划质检.批次号 )))+';' END)   ELSE '' END   )   +MAX ( ISNULL ( V计划质检.备注 , '' ) ) AS 备注,    MAX ( V计划质检.委外单号 ) AS 委外单号    FROM    (    SELECT     编号 ,  验收时间 制表日期 ,  工序 ,  工废数 ,  料废数 ,     合格数 ,  回用数 , 0 虚拟合格数 ,料废说明,     操作人 ,     检验人 ,  回用说明 ,       工废说明 ,     验收点评 AS 备注 ,     作业顺序 ,  投产号 ,  补加 ,     NULL AS 委外单号 ,     CASE WHEN 工序='加工' THEN 前道计划编号 ELSE 编号 END AS 前道计划编号,批次号,质量等级   FROM     计划生产 AS 计划生产_1  WITH ( NOLOCK )    UNION ALL    SELECT     编号 ,  制表日期 ,  工序 ,  工废数 ,  料废数 ,     合格数 ,  回用数 , 虚拟合格数 , 料废说明, 操作人 ,  检验人 ,     回用说明 ,  工废说明 ,  备注 ,  作业顺序 ,  投产号 ,     补加 ,  委外单号 ,  前道计划编号,批次号,质量等级   FROM     质检批量   WITH ( NOLOCK )    )  V计划质检    GROUP BY 投产号,补加,前道计划编号,作业顺序,工序   ) AS V计划质检 ON V计划质检.作业顺序 = 铸件作业路线.作业顺序    AND V计划质检.投产号 = 计划投产.投产号   AND V计划质检.补加 = 计划生产.补加   AND V计划质检.前道计划编号=计划生产.编号   LEFT OUTER JOIN (   SELECT     路线模板名称,    MAX ( 作业顺序 ) AS 作业顺序   FROM     铸件作业路线流程卡 AS 铸件作业路线_1 WITH ( NOLOCK )   WHERE     ( 自定义模板 = 1 ) AND      ( 作业工序 IN ( '打磨','任务下达' ) )   GROUP  BY     路线模板名称 ) AS V路线熔炼顺序 ON V路线熔炼顺序.路线模板名称 = 计划投产.路线方案 ) tmp_count
### Cause: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:128)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 42 more
Caused by: com.github.pagehelper.PageException: 不支持该SQL转换为分页查询!
	at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:106)
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:84)
	at com.github.pagehelper.dialect.helper.SqlServerDialect.getPageSql(SqlServerDialect.java:112)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:98)
	at com.ruoyi.mybatis_interceptor.MybatisResultInterceptor.interceptPageHelper(MybatisResultInterceptor.java:279)
	at com.ruoyi.mybatis_interceptor.MybatisResultInterceptor.intercept(MybatisResultInterceptor.java:70)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy181.queryCursor(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:124)
	... 48 more
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)
	at com.github.pagehelper.parser.SqlServerParser.convertToPageSql(SqlServerParser.java:104)
	... 56 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "WITH" "WITH"
    at line 26, column 8.

Was expecting one of:

    ","
    ";"
    "ACTION"
    "ANY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHAR"
    "COLUMN"
    "COLUMNS"
    "COMMENT"
    "COMMIT"
    "CONNECT"
    "CROSS"
    "DESCRIBE"
    "DO"
    "ENABLE"
    "END"
    "EXCEPT"
    "EXTRACT"
    "FIRST"
    "FN"
    "FOLLOWING"
    "FOR"
    "FULL"
    "GROUP"
    "HAVING"
    "INDEX"
    "INNER"
    "INSERT"
    "INTERSECT"
    "INTERVAL"
    "ISNULL"
    "JOIN"
    "KEY"
    "LAST"
    "LEFT"
    "MATERIALIZED"
    "MINUS"
    "NATURAL"
    "NO"
    "NULLS"
    "OPEN"
    "ORDER"
    "OVER"
    "PARTITION"
    "PATH"
    "PERCENT"
    "PIVOT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SIBLINGS"
    "START"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TOP"
    "TRUNCATE"
    "TYPE"
    "UNION"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "WHERE"
    "XML"
    "ZONE"
    <EOF>
    <K_DATETIMELITERAL>
    <K_DATE_LITERAL>
    <S_CHAR_LITERAL>
    <S_IDENTIFIER>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:20872)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:20722)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:80)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:36)
	... 57 more
```
## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
最新版本已经可以解析该SQL
