### ISSUE TITLE
重启的时候报 java.lang.NullPointerException

### ISSUE THREAD

**Issue by bukebuhao** [pagehelper/Mybatis-PageHelper#470]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 4.0.0
* 数据库类型和版本: mysql5.6
* JDBC_URL: com.mysql.jdbc.Driver useUnicode=true&characterEncoding=gbk

#### 分页参数

```java
PageHelper.startPage(1, 10);

```
仅系统重启的时候，偶发空异常

### 完整异常信息

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
        at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
        ... 71 more
Caused by: java.lang.NullPointerException
        at com.github.miemiedev.mybatis.paginator.OffsetLimitInterceptor.intercept(OffsetLimitInterceptor.java:69)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:60)
        at com.sun.proxy.$Proxy96.query(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:386)
        at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:329)
        at com.github.pagehelper.PageHelper.intercept(PageHelper.java:150)

**Comment by Jadmin3** [comment]
@bukebuhao 看来大神也有出bug的时候！
