### ISSUE TITLE
执行explain语句异常问题

### ISSUE THREAD

**Issue by sureding** [pagehelper/Mybatis-PageHelper#503]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 完整异常信息

Caused by: java.lang.ClassCastException: net.sf.jsqlparser.statement.ExplainStatement cannot be cast to net.sf.jsqlparser.statement.select.Select
	at com.github.pagehelper.parser.CountSqlParser.getSmartCountSql(CountSqlParser.java:185)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getCountSql(AbstractHelperDialect.java:78)
	at com.github.pagehelper.PageHelper.getCountSql(PageHelper.java:78)
	at com.github.pagehelper.util.ExecutorUtil.executeAutoCount(ExecutorUtil.java:130)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:150)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:97)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy9.query(Unknown Source)
	at com.github.findslow.executor.BaseExplainExecutor.execute(BaseExplainExecutor.java:56)
	at com.github.findslow.executor.Query4ExplainExecutor.execute(Query4ExplainExecutor.java:13)
	at com.github.findslow.FindSlowSqlPlugin.findSlowSql(FindSlowSqlPlugin.java:90)
	at com.github.findslow.FindSlowSqlPlugin.intercept(FindSlowSqlPlugin.java:40)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy9.query(Unknown Source)

 

## 功能建议
建议考虑explain的语句问题

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
不支持在实际查询数据中使用 explain
