### ISSUE TITLE
对两个仅LIMIT语句不一致的SQL作分表查询偶尔会出错

### ISSUE THREAD

**Issue by picc-lu** [pagehelper/Mybatis-PageHelper#526]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.1.11
* 数据库类型和版本: MySQL 8.0.13

#### 分页参数

```java
PageHelper.startPage(pageNum, pageSize);
// 查询有时会成功，有时会失败报异常
List<User> users = UserDao.listUsers(chooseTime);
```

#### 原 SQL

```java
public interface UserDao extends BaseDao<User> {
    // 实际语句更复杂，已简化
    // 两句SQL的差别仅仅是一个有“LIMIT #{offset}, #{limit}”，一个没有
    @Select("SELECT * FROM sys_user WHERE choose_time<#{chooseTime}")
    List<User> listUsers(@Param("chooseTime") Timestamp chooseTime);

    // 因某些原因，含有“LIMIT #{offset}, #{limit}”的这个语句暂时不能删除
    // 尝试过暂时将此方法、使用到此方法的语句注释掉，就不会出错了
    @Select("SELECT * FROM sys_user WHERE choose_time<#{chooseTime} LIMIT #{offset}, #{limit}")
    List<User> listUsers(@Param("chooseTime") Timestamp chooseTime, @Param("offset") int offset, @Param("limit") int limit);
}
```

#### 期望的结果：

按pageNum和pageSize正常查出Users列表

### 完整异常信息

```
Caused by: org.apache.ibatis.binding.BindingException: Parameter 'offset' not found. Available parameters are [chooseTime, param1]
        at org.apache.ibatis.binding.MapperMethod$ParamMap.get(MapperMethod.java:212)
        at org.apache.ibatis.reflection.wrapper.MapWrapper.get(MapWrapper.java:45)
        at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
        at com.baomidou.mybatisplus.core.executor.AbstractBaseExecutor.createCacheKey(AbstractBaseExecutor.java:81)
        at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.createCacheKey(MybatisCachingExecutor.java:248)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:83)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy323.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
除了额外的RowBounds参数可以用于同名方法多态外，其他情况别用。
