### ISSUE TITLE
 getLocalPage()方法获取的Page对象为null

### ISSUE THREAD

**Issue by Edgar-cn** [pagehelper/Mybatis-PageHelper#567]
- 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* 最新版本
#### 定位到的代码部分

```java
        String sql = boundSql.getSql();
        Page page = getLocalPage();
        //支持 order by
        String orderBy = page.getOrderBy();
```

### 完整异常信息

```
java.lang.NullPointerException: null
	at com.github.pagehelper.dialect.AbstractHelperDialect.getPageSql(AbstractHelperDialect.java:188)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:101)
	at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:196)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:107)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy143.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy89.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy98.findList(Unknown Source)
	at com.sunnyit.safe.core.persistence.BaseService.findPage(BaseService.java:72)
	at com.sunnyit.safe.core.persistence.BaseService$$FastClassBySpringCGLIB$$9ab2108e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)

```

### 错误描述
’‘’
在分页查询的时候，偶尔会出现上面的错误
 getLocalPage()获取的Page对象为null
所以再执行下一步   page.getOrderBy()   的时候抛出空指针异常
’‘’

**Comment by 18311026809** [comment]
您好，
请问您遇到这种问题的时候，是否都是对工程重新构建部署以后发生的？
最近我也经常遇到这种问题。

**Comment by Edgar-cn** [comment]
@liziWanggg 
兄弟怎么样，你解决了吗？
你说的重新布局部署是指什么？基础的架构并没有太大改变，只是提升了springboot的版本，从1.x到了2.x并修改了冲突使其正常运行。

**Comment by liziWanggg** [comment]
没有啊，我这就每次重启发现有这个问题。翻了翻19年好像就有人提过这个bug，但是并没有人回复




| |
王颖
|
|
邮箱：18311026809@163.com
|

签名由 网易邮箱大师 定制

在2020年12月10日 10:00，Edgar-cn 写道：

@liziWanggg
兄弟怎么样，你解决了吗？
你说的重新布局部署是指什么？基础的架构并没有太大改变，只是提升了springboot的版本，从1.x到了2.x并修改了冲突使其正常运行。

**Comment by abel533** [comment]
能不能提供调用分页插件部分的代码？
