### ISSUE TITLE
informix版本10分页查询sql语法错误，不是count(*)问题。

### ISSUE THREAD

**Issue by qujun123** [pagehelper/Mybatis-PageHelper#615]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.2.9
* 数据库类型和版本: 10.00.FC10
* JDBC_URL: jdbc:informix-sqli://10.1.xx.xxx:7788/ismp02:informixserver=server218;NEWCODESET=GBK,8859-1,819;IFX_TRIMTRAILINGSPACES=1;IFX_USE_STRENC=true

### SQL 解析错误
nested exception is java.sql.SQLSyntaxErrorException: A syntax error has occurred.
#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL
```sql
SELECT  FIRST ?  * FROM (  SELECT * FROM ctx_weboperator               WHERE status = '0'                            and mngrtype = ?       order By createtime desc  ) TEMP_T
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息
```
16:17:42.574 DEBUG c.c.m.OperatorMapper.selectByPages - ==>  Preparing: SELECT FIRST ? * FROM ( SELECT * FROM ctx_weboperator WHERE status = '0' and mngrtype = ? order By createtime desc ) TEMP_T
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@48b0a3fd]
16:17:42.667 ERROR o.s.b.w.s.support.ErrorPageFilter - Forwarding to error page from request [/getallCustomer] due to exception [
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: A syntax error has occurred.
### The error may exist in file [/home/mixctx/webapps/yncentrexMngr/WEB-INF/classes/mapper/WeboperatorMapper.xml]
### The error may involve com.centrex.mapper.OperatorMapper.selectByPages
### The error occurred while executing a query
### SQL: SELECT  FIRST ?  * FROM (  SELECT * FROM ctx_weboperator               WHERE status = '0'                            and mngrtype = ?       order By createtime desc  ) TEMP_T
### Cause: java.sql.SQLSyntaxErrorException: A syntax error has occurred.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: A syntax error has occurred.]
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: A syntax error has occurred.
### The error may exist in file [/home/mixctx/webapps/yncentrexMngr/WEB-INF/classes/mapper/WeboperatorMapper.xml]
### The error may involve com.centrex.mapper.OperatorMapper.selectByPages
### The error occurred while executing a query
### SQL: SELECT  FIRST ?  * FROM (  SELECT * FROM ctx_weboperator               WHERE status = '0'                            and mngrtype = ?       order By createtime desc  ) TEMP_T
### Cause: java.sql.SQLSyntaxErrorException: A syntax error has occurred.
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: A syntax error has occurred.
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:235)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy481.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy482.selectByPages(Unknown Source)
        at com.centrex.ctr.PrivileCtr.getallCustomer(PrivileCtr.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.centrex.util.ControllerFileter.doFilter(ControllerFileter.java:27)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: A syntax error has occurred.
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:465)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
        at com.informix.jdbc.IfxSqli.addException(IfxSqli.java:3191)
        at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3472)
        at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2379)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2304)
        at com.informix.jdbc.IfxSqli.executePrepare(IfxSqli.java:1267)
        at com.informix.jdbc.IfxPreparedStatement.setupExecutePrepare(IfxPreparedStatement.java:315)
        at com.informix.jdbc.IfxPreparedStatement.processSQL(IfxPreparedStatement.java:296)
        at com.informix.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:185)
        at com.informix.jdbc.IfxSqliConnect.createPreparedStmt(IfxSqliConnect.java:6449)
        at com.informix.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2608)
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
        at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.ibatis.logging.jdbc.ConnectionLogger.invoke(ConnectionLogger.java:55)
        at com.sun.proxy.$Proxy145.prepareStatement(Unknown Source)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86)
        at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
        at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:87)
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
        at com.github.pagehelper.util.ExecutorUtil.pageQuery(ExecutorUtil.java:209)
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:107)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at com.sun.proxy.$Proxy552.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
        ... 72 common frames omitted
Caused by: java.sql.SQLException: null
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:474)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:443)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:394)
        at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3477)
        ... 106 common frames omitted
```
异常信息放在这里

## 功能建议

详细说明，尽可能提供(伪)代码示例。、
使用informix版本11或者12，sql不会报错。

**Comment by abel533** [comment]
应该是语法不兼容的问题。
你可以实现一个版本10的分页实现。
