### ISSUE TITLE
Mysql语句中使用matched 引发JSQLParserException异常

### ISSUE THREAD

**Issue by Layofhan** [pagehelper/Mybatis-PageHelper#645]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

我这边设置了properties.setProperty("helperDialect", "mysql");
且matched并不是mysql的关键字 为什么还会报这种错误？我应该需要怎么消除

### 使用环境

* PageHelper 版本: 5.1.5
* 数据库类型和版本: mysql  Ver 8.0.16 for el7 on x86_64 
* JDBC_URL: jdbc:mysql://Xxxxx/xxx?serverTimezone=GMT%2B8&setUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

#### 分页参数

```java
PageHelper.startPage(1, 10， "matched desc");
xxMapper.select(model);
```

#### 原 SQL

```sql
select matched from xxx where xxx = xxx
```

#### 期望的结果：

```sql
select matched from xxx where xxx = xxx limit 10 order by matched desc
```

### 完整异常信息

```
Error querying database.  Cause: com.github.pagehelper.PageException: 处理排序失败: net.sf.jsqlparser.JSQLParserException
The error may exist in file [D:/xxx/XxxxMapper.xml]
The error may involve com.XxxxeMapper.queryBy_COUNT
 The error occurred while handling results
SQL: select count(0) from (select         id, matched , trans_source, fg_trade_no, fg_refund_no, trans_no, amount, channel_code, bank_mch_id,         third_order_id, '' as trans_start_time, trans_finish_time, payer_acc_num, payer_acc_name, direct_pay_way, state as tradeState,         fee, pay_type, '' as allocation_sub_order_no, '' as allocation_amount, '' as allocation_outer_mch_id, ent_num         from bank_bill_record where                   1=1 and ent_num = ? and channel_code = ? and         trans_finish_time >= ? and trans_finish_time <= ?) tmp_count
Cause: com.github.pagehelper.PageException: 处理排序失败: net.sf.jsqlparser.JSQLParserException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 86 common frames omitted
Caused by: com.github.pagehelper.PageException: 处理排序失败: net.sf.jsqlparser.JSQLParserException
	at com.github.pagehelper.parser.OrderByParser.converToOrderBySql(OrderByParser.java:64)
	at com.github.pagehelper.dialect.AbstractHelperDialect.getPageSql(AbstractHelperDialect.java:173)
	at com.github.pagehelper.PageHelper.getPageSql(PageHelper.java:98)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:139)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy121.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 92 common frames omitted
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:55)
	at com.github.pagehelper.parser.OrderByParser.converToOrderBySql(OrderByParser.java:52)
	... 98 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "matched" "MATCHED"
    at line 2, column 13.

Was expecting one of:

    "("
    "*"
    "+"
    "-"
    ":"
    "?"
    "@"
    "@@"
    "ACTION"
    "ANY"
    "CASCADE"
    "CASE"
    "CAST"
    "COLUMN"
    "COMMIT"
    "DO"
    "DOUBLE"
    "ENABLE"
    "END"
    "EXTRACT"
    "FIRST"
    "FOLLOWING"
    "GROUP_CONCAT"
    "IF"
    "INDEX"
    "INSERT"
    "INTERVAL"
    "KEY"
    "LAST"
    "LEFT"
    "MATERIALIZED"
    "NO"
    "NULL"
    "NULLS"
    "OPEN"
    "OVER"
    "PARTITION"
    "PERCENT"
    "PRECISION"
    "PRIMARY"
    "PRIOR"
    "RANGE"
    "REPLACE"
    "RIGHT"
    "ROW"
    "ROWS"
    "SEPARATOR"
    "SET"
    "SIBLINGS"
    "TABLE"
    "TEMP"
    "TEMPORARY"
    "TRUNCATE"
    "UNSIGNED"
    "VALUE"
    "VALUES"
    "XML"
    "{d"
    "{fn"
    "{t"
    "{ts"
    "~"
    <K_DATETIMELITERAL>
    <K_TIME_KEY_EXPR>
    <S_CHAR_LITERAL>
    <S_DOUBLE>
    <S_HEX>
    <S_IDENTIFIER>
    <S_LONG>
    <S_QUOTED_IDENTIFIER>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:18047)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:17900)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItem(CCJSqlParser.java:3528)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectItemsList(CCJSqlParser.java:3368)
	at net.sf.jsqlparser.parser.CCJSqlParser.PlainSelect(CCJSqlParser.java:2930)
	at net.sf.jsqlparser.parser.CCJSqlParser.SetOperationList(CCJSqlParser.java:3107)
	at net.sf.jsqlparser.parser.CCJSqlParser.SelectBody(CCJSqlParser.java:2824)
	at net.sf.jsqlparser.parser.CCJSqlParser.Select(CCJSqlParser.java:2817)
	at net.sf.jsqlparser.parser.CCJSqlParser.SingleStatement(CCJSqlParser.java:133)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:81)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:53)
	... 99 common frames omitted
```

**Comment by tanoak10** [comment]
这个错误是由jsqlparser 抛出的，并不是pagehelper，解决方式你的sql用别名，具体原因可以去看这个类
net.sf.jsqlparser.parser.CCJSqlParserConstants

**Comment by tanoak10** [comment]
matched 属于关键字

**Comment by Layofhan** [comment]
> 这个错误是由jsqlparser 抛出的，并不是pagehelper，解决方式你的sql用别名，具体原因可以去看这个类 net.sf.jsqlparser.parser.CCJSqlParserConstants

感觉说明，看了下page作者在最新版是做了一个降级的处理。然后我的解决方案是修改了字段名。

**Comment by Layofhan** [comment]
> matched 属于关键字

在oracle中应该是 但是在mysql中应该不是。

**Comment by Layofhan** [comment]
jsqlparser 好像并没有针对不同的数据库 做不同的关键词处理。
