### ISSUE TITLE
用pagehelper-spring-boot-starter组件1.4.1版本，mybatis通过oscarJDBC-1.0.jar查询神通数据库时，会报Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0问题

### ISSUE THREAD

**Issue by daxue2017** [pagehelper/Mybatis-PageHelper#651]
报错如下：
```
Caused by: org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
### The error may exist in URL [jar:file:/usr/local/server/abcss.jar!/BOOT-INF/classes!/mapper/TaskinfoMapper.xml]
### The error may involve com.github.wxiaoqi.security.abcss.mapper.TaskinfoMapper.selectTaskInProgress_COUNT
### The error occurred while handling results
### SQL: SELECT count(0) FROM TaskInfo WHERE TaskState != 3 AND TaskState != 103 AND (MeetingNo LIKE '%%' OR MeetingTitle LIKE '%%')
### Cause: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.4.jar!/:3.4.4]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150) ~[mybatis-3.4.4.jar!/:3.4.4]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.4.jar!/:3.4.4]
        at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
        ... 94 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_161]
        at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_161]
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:113) ~[pagehelper-5.0.3.jar!/:na]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.4.jar!/:3.4.4]
        at com.sun.proxy.$Proxy211.query(Unknown Source) ~[na:na]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.4.jar!/:3.4.4]
        ... 99 common frames omitted
```

这怎么修改啊

**Comment by abel533** [comment]
先解决这里的BUG再试试 `MeetingNo LIKE '%%' OR MeetingTitle LIKE '%%'`。
