### ISSUE TITLE
执行分页 sql 解析失败

### ISSUE THREAD

**Issue by 2259289435** [pagehelper/Mybatis-PageHelper#698]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 1.3.0
* 数据库类型和版本: mysql8
* JDBC_URL: ?useUnicode=true&useSSL=false&autoReconnect=true&failOverReadOnly=false

#### 分页参数

```java
PageHelper.startPage(1, 10);
xxMapper.select(model);
```

#### 原 SQL

```sql
Caused by: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: select count(0) from ( 
select
            a.region_id region,
            a.org_id organizeId,
            a.meal_type_id mealTypeId
        from (
            
            select
                b.region_id,
                b.org_id,
                a.meal_type_id
            from (
                
                select
                    a.customer_id,
                    a.meal_type_id
                from cai_dining_calendar a
                 WHERE a.eat_flag = 1 and a.dining_date = ? and a.tenant_code = ? 
            ) a inner join (select * from json_table (
                    
                    ?,
                    '$[*]' COLUMNS (
                        `region_id` bigint PATH '$.a' ERROR ON ERROR,
                        `org_id` bigint PATH '$.b' ERROR ON ERROR,
                        `customer_id` bigint PATH '$.c' ERROR ON ERROR
                    )
            ) b) b on a.customer_id = b.customer_id
            group by b.region_id,b.org_id,a.meal_type_id
        ) a
        order by a.region_id,a.org_id,a.meal_type_id
        /*keep orderby*/
```

#### 期望的结果：

```sql
select * from xxx where xxx = xxx limit 10
```

### 完整异常信息

```
异常信息放在这里
Caused by: net.sf.jsqlparser.JSQLParserException: null
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:65)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:40)
	at com.baomidou.mybatisplus.extension.parser.JsqlParserSupport.parserSingle(JsqlParserSupport.java:34)
	... 129 common frames omitted
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "(" "("
    at line 19, column 54.

Was expecting one of:

    ")"
    ","
    "ACTION"
    "ANY"
    "APPLY"
    "AS"
    "BYTE"
    "CASCADE"
    "CAST"
    "CHANGE"

### 其他类型的错误

## 功能建议

不分页没问题，加了分页就报错。

**Comment by abel533** [comment]
sql特殊解析不了，这个错影响使用吗？
