### ISSUE TITLE
执行手动设置的 count 查询，count结果返回为空报错

### ISSUE THREAD

**Issue by YLongGe** [pagehelper/Mybatis-PageHelper#713]
- [x] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

com.github.pagehelper.util.ExecutorUtil#executeManualCount.countResultList 可否加个判空

### 使用环境

* PageHelper 版本: 1.3.0
* 数据库类型和版本: Mysql8.0

#### 分页参数

```java
PageHelper.startPage(1, 10);
<select id="countTest_COUNT" resultType="java.lang.Long">
        select
            COUNT(0)
        from table
        where merchant_id = 0
        group by
            goods_id, shop_goods_id, sub_goods_id
    </select>
```
#### 原 SQL
```sql
select COUNT(0)
 FROM table
 WHERE merchant_id = 0 group by goods_id, shop_goods_id, sub_goods_id;
```
----

### 完整异常信息

```
异常信息放在这里
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.github.pagehelper.util.ExecutorUtil.executeManualCount(ExecutorUtil.java:130)
	at com.github.pagehelper.PageInterceptor.count(PageInterceptor.java:144)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:100)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy219.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
```
## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by YLongGe** [comment]
com.github.pagehelper.util.ExecutorUtil#executeManualCount.countResultList 可否加个判空

**Comment by abel533** [comment]
Pagehelper 5.3.0和starter1.4.0以后版本都不存在这个问题，升级到最新就行。
