### ISSUE TITLE
SpringBoot3运行native-image报错 

### ISSUE THREAD

**Issue by weifengze** [pagehelper/Mybatis-PageHelper#765]
- [ √] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 1.4.7
* 数据库类型和版本: MySQL 8.0.33
* JDBC_URL: 

### 完整异常信息

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration': java.lang.InstantiationException: com.github.pagehelper.PageHelper
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.cmcc.transport.network.TransportNetworkConstructionDrawingsApplicationKt.main(TransportNetworkConstructionDrawingsApplication.kt:17)
Caused by: com.github.pagehelper.PageException: java.lang.InstantiationException: com.github.pagehelper.PageHelper
	at com.github.pagehelper.PageInterceptor.setProperties(PageInterceptor.java:219)
	at com.github.pagehelper.autoconfigure.PageHelperAutoConfiguration.afterPropertiesSet(PageHelperAutoConfiguration.java:65)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 16 common frames omitted
Caused by: java.lang.InstantiationException: com.github.pagehelper.PageHelper
	at java.base@17.0.8/java.lang.Class.newInstance(DynamicHub.java:639)
	at com.github.pagehelper.PageInterceptor.setProperties(PageInterceptor.java:217)
	... 19 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.github.pagehelper.PageHelper.<init>()
	at java.base@17.0.8/java.lang.Class.checkMethod(DynamicHub.java:1038)
	at java.base@17.0.8/java.lang.Class.getConstructor0(DynamicHub.java:1204)
	at java.base@17.0.8/java.lang.Class.newInstance(DynamicHub.java:626)
	... 20 common frames omitted
```

## 功能建议

详细说明，尽可能提供(伪)代码示例。

**Comment by tsingheng** [comment]
It is working for me.
```
@Configuration(proxyBeanMethods = false)
@ImportRuntimeHints(PageHelperNativeConfiguration.PageHelperRuntimeHintsRegistrar.class)
public class PageHelperNativeConfiguration {

    @Bean
    public PageHelperBeanFactoryInitializationAotProcessor pageHelperBeanFactoryInitializationAotProcessor() {
        return new PageHelperBeanFactoryInitializationAotProcessor();
    }

    static class PageHelperRuntimeHintsRegistrar implements RuntimeHintsRegistrar {

        @Override
        public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
            Stream.of(
                    PageHelper.class,
                    MySqlDialect.class,
                    BoundSql.class
            ).forEach(x -> hints.reflection().registerType(x, MemberCategory.values()));
        }
    }

    static class PageHelperBeanFactoryInitializationAotProcessor
            implements BeanFactoryInitializationAotProcessor, BeanRegistrationExcludeFilter {

        @Override
        public BeanFactoryInitializationAotContribution processAheadOfTime(ConfigurableListableBeanFactory beanFactory) {
            return (context, code) -> {
                RuntimeHints hints = context.getRuntimeHints();
                hints.proxies().registerJdkProxy(Executor.class);
            };
        }

        @Override
        public boolean isExcludedFromAotProcessing(RegisteredBean registeredBean) {
            return false;
        }
    }
}
```

**Comment by weifengze** [comment]
谢谢，有时间我试一下！

**Comment by jonesmith518** [comment]
thanks it worked, helps me alot
