### ISSUE TITLE
达梦数据库hint兼容group by但是PageHelper分页不支持hint

### ISSUE THREAD

**Issue by robin-xl** [pagehelper/Mybatis-PageHelper#826]
- [ ] 我已在 [issues](https://github.com/pagehelper/Mybatis-PageHelper/issues) 搜索类似问题，并且不存在相同的问题.

### 使用环境

* PageHelper 版本: 5.3.2
* 数据库类型和版本: 达梦
* pagehelper.helperDialect=dm
* JDBC_URL: spring.datasource.url=jdbc:dm://xx.xx.xx.xx:xxx/xxxxx

#### 分页参数

```java
PageHelper.startPage(1, 10).doselectpageinfo(()-> {pluginMapper.page(param)});
```

#### 原 SQL

```sql
SELECT /*+ GROUP_OPT_FLAG(1) */ p.* FROM cw_cc_plugin p LEFT JOIN cw_cc_plugin_tag pt ON pt.PLUGIN_ID = p.ID WHERE p.BUSINESS_ID = ? GROUP BY p.ID
```

#### 期望的结果：

```sql
SELECT  /*+ GROUP_OPT_FLAG(1) */  count(0) FROM (SELECT p.* FROM cw_cc_plugin p LEFT JOIN cw_cc_plugin_tag pt ON pt.PLUGIN_ID = p.ID WHERE p.BUSINESS_ID = ? GROUP BY p.ID) table_count
```

### 完整异常信息

```
org.springframework.dao.DataIntegrityViolationException: 
### Error querying database.  Cause: dm.jdbc.driver.DMException: 第1 行附近出现错误:
不是 GROUP BY 表达式
### The error may exist in file [D:\cwos\cwos-copilot\cwos-copilot-starter\target\classes\mybatis\dm\plugin\PluginMapper.xml]
### The error may involve com.cloudwalk.copilot.data.mapper.plugin.PluginMapper.page_COUNT
### The error occurred while executing a query
### SQL: SELECT count(0) FROM (SELECT /*+ GROUP_OPT_FLAG(1) */ p.* FROM cw_cc_plugin p LEFT JOIN cw_cc_plugin_tag pt ON pt.PLUGIN_ID = p.ID WHERE p.BUSINESS_ID = ? GROUP BY p.ID) table_count
### Cause: dm.jdbc.driver.DMException: 第1 行附近出现错误:
不是 GROUP BY 表达式
; 第1 行附近出现错误:
不是 GROUP BY 表达式; nested exception is dm.jdbc.driver.DMException: 第1 行附近出现错误:
不是 GROUP BY 表达式
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy132.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
```

## 功能建议

分页计算count(0) 的时候能把原来的hint信息放到第一个select的后面来兼容

详细说明，尽可能提供(伪)代码示例。

**Comment by abel533** [comment]
无法支持这种hint规则，jsqlparser应该无法解析才变成这种sql。
